# Generated by Django 5.0.6 on 2024-07-07 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addon', '0002_divarusers_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='post_token',
            field=models.CharField(default='', max_length=9),
            preserve_default=False,
        ),
    ]
