# Generated by Django 5.0.6 on 2024-07-11 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addon', '0003_product_post_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AlterField(
            model_name='product',
            name='post_token',
            field=models.CharField(max_length=9, primary_key=True, serialize=False),
        ),
    ]
